name: crucible-ci

on:
  # run on push or pull request events for the master branch only
  pull_request:
    branches: [ master ]

  # allow for manual invocation from the actions tab
  workflow_dispatch:

jobs:
  crucible-ci:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout bench-uperf
      uses: actions/checkout@v2
      with:
        path: bench-uperf

    - name: Checkout crucible-ci
      uses: actions/checkout@v2
      with:
        repository: perftool-incubator/crucible-ci
        ref: main
        path: crucible-ci

    - name: Run crucible-ci->integration-tests
      uses: ./crucible-ci/.github/actions/integration-tests
      with:
        artifact_tag: "uperf"
        ci_target: "uperf"
        ci_target_dir: ${{ github.workspace }}/bench-uperf
        scenarios: "uperf"
        repeat_runs: "no"
        run_samples: "1"
